### ISSUE TITLE
analyzeReplays.py :- concurrent.futures._base.CancelledError

### ISSUE THREAD

**Issue by dannyp777** [Jylpah/blitz-tools#1]
Hi Jylpah,
It's been a long time since I have used a console or seriously looked at code. I updated my Python to the latest version (3.7.1 64bit), installed the pip libraries, and downloaded the wotblitz apk from apkpure.com. Successfully ran getTankopedia.py, ExtractTankopedia.py, and wotbreplay_uploader.py to get my json files .
However analyzeReplays.py has failed on 4 different json files, not all with the same debug output.
Here are the files: 
[https://drive.google.com/drive/folders/19cHgmARM3lHtdRTj_3WPmEzZ9ihYIxDS?usp=sharing]

I will have a little look around the code but here is some console output:

C:\Users\Danny\Desktop\WoT Blitz\tools\blitz-tools-master
λ python analyzeReplays.py -v -d .\20181021_2102_ARL_44_savanna.json
DEBUG: __init__(): WG aiohttp session initiated
DEBUG: main(): Task 0 started
DEBUG: main(): Task 1 started
DEBUG: main(): Task 2 started
DEBUG: main(): Task 3 started
DEBUG: main(): Task 4 started
DEBUG: main(): Task 5 started
DEBUG: main(): Task 6 started
DEBUG: main(): Waiting for the replay scanner to finish
DEBUG: mkReplayQ(): File added to queue: .\20181021_2102_ARL_44_savanna.json
DEBUG: mkReplayQ(): Finished
DEBUG: main(): Scanner finished. Waiting for replay readers to finish the queue
DEBUG: main(): Replays read. Cancelling Readers and analyzing results
DEBUG: processTankStats(): Create player/tank stats queue
DEBUG: processTankStats(): Starting player/tank stats queue workers
Traceback (most recent call last):
  File "analyzeReplays.py", line 595, in <module>
    asyncio.run(main(sys.argv[1:]), debug=True)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\Danny\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
concurrent.futures._base.CancelledError

I am running it all from my "C:\Users\Danny\Desktop\WoT Blitz\tools\blitz-tools-master" path, with all work files in the same folder with the scripts.

Cheers,
Danny P (Torintermage/lotharn)

**Comment by Jylpah** [comment]
Thank you for your bug report. I run into the same problem myself and I think the latest commit [`cf10dae`](https://github.com/Jylpah/blitz-tools/commit/cf10dae8752a69548aa7288122857056c943a1ea#diff-93fdff852c32017943bb4782773ec968) fixed it.
