### ISSUE TITLE
kv220 errors

### ISSUE THREAD

**Issue by MjrEazy** [Jylpah/blitz-tools#25]
ERROR: tank_str2name(): Tank KV-220 not found

when running the upload script, I didn't try the script to refresh the tanks.json as it's in tanks.json as "KV-220 Beta-Test"...

They upload to wotinsepctor ok.

**Comment by Jylpah** [comment]
Could you please send the replay file itself to jylpah@gmail.com. The replay files store the tank as a string that has to be converted based on tanks.json's "userStrings".

**Comment by Jylpah** [comment]
Do `git pull` again to get new `tanks.json`. It *should* fix the issue.

**Comment by Jylpah** [comment]
_extensive_ testing confirmed the fix works :-)
